import pandas as pd
import pandas_ta as ta


def get_algorithm_name_list():
	df=pd.DataFrame()
	df.ta.indicators()
	ind_list = df.ta.indicators(as_list=True)
	algorithm_name_list=[(i, i.upper().replace('_',' ')) for i in ind_list]
	return algorithm_name_list

print(get_algorithm_name_list())



# ----------------------------------------------------------------
# Candle Patterns:
#     2crows, 3blackcrows, 3inside, 3linestrike, 3outside, 3starsinsouth, 3whitesoldiers, abandonedbaby, advanceblock, belthold, breakaway, closingmarubozu, concealbabyswall, counterattack, darkcloudcover, doji, dojistar, dragonflydoji, engulfing, eveningdojistar, eveningstar, gapsidesidewhite, gravestonedoji, hammer, hangingman, harami, haramicross, highwave, hikkake, hikkakemod, homingpigeon, identical3crows, inneck, inside, invertedhammer, kicking, kickingbylength, ladderbottom, longleggeddoji, longline, marubozu, matchinglow, mathold, morningdojistar, morningstar, onneck, piercing, rickshawman, risefall3methods, separatinglines, shootingstar, shortline, spinningtop, stalledpattern, sticksandwich, takuri, tasukigap, thrusting, tristar, unique3river, upsidegap2crows, xsidegap3methods
# [('aberration', 'ABERRATION'), ('above', 'ABOVE'), ('above_value', 'ABOVE VALUE'), ('accbands', 'ACCBANDS'), ('ad', 'AD'), ('adosc', 'ADOSC'), ('adx', 'ADX'), ('alma', 'ALMA'), ('amat', 'AMAT'), ('ao', 'AO'), ('aobv', 'AOBV'), ('apo', 'APO'), ('aroon', 'AROON'), ('atr', 'ATR'), ('bbands', 'BBANDS'), ('below', 'BELOW'), ('below_value', 'BELOW VALUE'), ('bias', 'BIAS'), ('bop', 'BOP'), ('brar', 'BRAR'), ('cci', 'CCI'), ('cdl_pattern', 'CDL PATTERN'), ('cdl_z', 'CDL Z'), ('cfo', 'CFO'), ('cg', 'CG'), ('chop', 'CHOP'), ('cksp', 'CKSP'), ('cmf', 'CMF'), ('cmo', 'CMO'), ('coppock', 'COPPOCK'), ('cross', 'CROSS'), ('cross_value', 'CROSS VALUE'), ('cti', 'CTI'), ('decay', 'DECAY'), ('decreasing', 'DECREASING'), ('dema', 'DEMA'), ('dm', 'DM'), ('donchian', 'DONCHIAN'), ('dpo', 'DPO'), ('ebsw', 'EBSW'), ('efi', 'EFI'), ('ema', 'EMA'), ('entropy', 'ENTROPY'), ('eom', 'EOM'), ('er', 'ER'), ('eri', 'ERI'), ('fisher', 'FISHER'), ('fwma', 'FWMA'), ('ha', 'HA'), ('hilo', 'HILO'), ('hl2', 'HL2'), ('hlc3', 'HLC3'), ('hma', 'HMA'), ('hwc', 'HWC'), ('hwma', 'HWMA'), ('ichimoku', 'ICHIMOKU'), ('increasing', 'INCREASING'), ('inertia', 'INERTIA'), ('jma', 'JMA'), ('kama', 'KAMA'), ('kc', 'KC'), ('kdj', 'KDJ'), ('kst', 'KST'), ('kurtosis', 'KURTOSIS'), ('kvo', 'KVO'), ('linreg', 'LINREG'), ('log_return', 'LOG RETURN'), ('long_run', 'LONG RUN'), ('macd', 'MACD'), ('mad', 'MAD'), ('massi', 'MASSI'), ('mcgd', 'MCGD'), ('median', 'MEDIAN'), ('mfi', 'MFI'), ('midpoint', 'MIDPOINT'), ('midprice', 'MIDPRICE'), ('mom', 'MOM'), ('natr', 'NATR'), ('nvi', 'NVI'), ('obv', 'OBV'), ('ohlc4', 'OHLC4'), ('pdist', 'PDIST'), ('percent_return', 'PERCENT RETURN'), ('pgo', 'PGO'), ('ppo', 'PPO'), ('psar', 'PSAR'), ('psl', 'PSL'), ('pvi', 'PVI'), ('pvo', 'PVO'), ('pvol', 'PVOL'), ('pvr', 'PVR'), ('pvt', 'PVT'), ('pwma', 'PWMA'), ('qqe', 'QQE'), ('qstick', 'QSTICK'), ('quantile', 'QUANTILE'), ('rma', 'RMA'), ('roc', 'ROC'), ('rsi', 'RSI'), ('rsx', 'RSX'), ('rvgi', 'RVGI'), ('rvi', 'RVI'), ('short_run', 'SHORT RUN'), ('sinwma', 'SINWMA'), ('skew', 'SKEW'), ('slope', 'SLOPE'), ('sma', 'SMA'), ('smi', 'SMI'), ('squeeze', 'SQUEEZE'), ('squeeze_pro', 'SQUEEZE PRO'), ('ssf', 'SSF'), ('stc', 'STC'), ('stdev', 'STDEV'), ('stoch', 'STOCH'), ('stochrsi', 'STOCHRSI'), ('supertrend', 'SUPERTREND'), ('swma', 'SWMA'), ('t3', 'T3'), ('td_seq', 'TD SEQ'), ('tema', 'TEMA'), ('thermo', 'THERMO'), ('tos_stdevall', 'TOS STDEVALL'), ('trima', 'TRIMA'), ('trix', 'TRIX'), ('true_range', 'TRUE RANGE'), ('tsi', 'TSI'), ('tsignals', 'TSIGNALS'), ('ttm_trend', 'TTM TREND'), ('ui', 'UI'), ('uo', 'UO'), ('variance', 'VARIANCE'), ('vhf', 'VHF'), ('vidya', 'VIDYA'), ('vortex', 'VORTEX'), ('vp', 'VP'), ('vwap', 'VWAP'), ('vwma', 'VWMA'), ('wcp', 'WCP'), ('willr', 'WILLR'), ('wma', 'WMA'), ('xsignals', 'XSIGNALS'), ('zlma', 'ZLMA'), ('zscore', 'ZSCORE')]